In [ ]:
import numpy as np

# vector / array
a = np.array([1,2,3])
b = np.array([4,5,6])

# add two vectors
c = a + b
print('addition: ', c)

# multiply two vectors:
# - element-wise (Hadamard)
h = a*b
print('element-wise multiplication: ', h)
# - inner (dot) product
p = np.dot(a,b) # or simply: p = a@b
print('inner (dot) product: ', p)

# question: can we perform any of the above with different sizes of a and b?

addition:  [5 7 9]
element-wise multiplication:  [ 4 10 18]
inner (dot) product:  32


In [ ]:
# matrix
m = np.array( [ [1,2,3] , [4,5,6] ])
n = np.array( [ [11,12,13] , [14,15, 16] ])
k = np.array( [ [21,22] , [23,24] , [25,26] ])

print('n:')
print(n)
print('m:')
print(m)
print('k:')
print(k)

# addition: need to have same dimensions (same number of rows and columns)
s = m + n
print('addition: \n', m+n)

# multiply two matrices:
# - element-wise (Hadamard)
h = m*n
print('element-wise multiplication: \n', h)

# - typical product: columns of first same as rows of second
p = np.matmul(m,k) # 2x3 3x2 = 2x2
print('element-wise multiplication: \n', p)

n:
[[11 12 13]
 [14 15 16]]
m:
[[1 2 3]
 [4 5 6]]
k:
[[21 22]
 [23 24]
 [25 26]]
addition: 
 [[12 14 16]
 [18 20 22]]
element-wise multiplication: 
 [[11 24 39]
 [56 75 96]]
element-wise multiplication: 
 [[142 148]
 [349 364]]
